version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/data
    ports:
      - "8000:8000" 
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend: